services:
  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile.dev
    container_name: pull-request-desk-front
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    ports:
      - "8081:8081" # Metro bundler para React Native
    command: ["npm", "start"]

  backend:
    build:
      context: ./backend/app
      dockerfile: Dockerfile.dev
    container_name: pull-request-desk-back
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=mongodb://mongo:27017/my_database
    volumes:
      - ./backend/app:/app
      - ~/.m2:/root/.m2 # Para usar el caché de Maven
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
